name: "Enhance A Feature"
description: "To request a feature enhancement for the project."
labels: [ "Enhancement", "Discussion" ]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Please provide a short description of what you are looking forward to
        enhance or remove. Please include the story behind the idea to better
        visualize your case.
      placeholder: "E.g: 15cm noodle instead of 5cm - slurp up too quickly."
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expected Behavior
      description: >
        Please specify the expected behavior below.
      placeholder: "E.g: Noodle is at least 15cm longer."
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: >
        Please specify the any current behavior (e.g. workarounds).You may
        specify "Not Applicable" when it's not applicable.
      placeholder: "E.g: Noodle is 5cm long and slupped up in 2 seconds. Not enjoyable."
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Associated Data Files
      description: >
        Please drag and drop all the necessary data files (e.g. screenshot,
        logs, etc) into the box below. Each successful uploads will transform
        into their unique URL link on its own.
      placeholder: "Please drag and drop it here."
    validations:
      required: false
